server:
  port: 9091
  servlet.context-path: /secure-banking-api


spring:
  application:
    name: secure-banking-api

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/secure_banking_db
    username: root
    password: mariadb

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/securebank/protocol/openid-connect/certs

keycloak:
  resource: secure-banking-api

logging:
  level:
    org.springframework.security: DEBUG